In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import surprise

In [2]:
users = pd.read_csv('BX-Users.csv',sep=';') 
items = pd.read_csv('BX-Books.csv',sep=';',error_bad_lines=False)
ratings = pd.read_csv('BX-Book-Ratings.csv',sep=';')
ratings = ratings[ratings['Book-Rating'] > 0]

Skipping line 6452: expected 8 fields, saw 9
Skipping line 43667: expected 8 fields, saw 10
Skipping line 51751: expected 8 fields, saw 9

Skipping line 92038: expected 8 fields, saw 9
Skipping line 104319: expected 8 fields, saw 9
Skipping line 121768: expected 8 fields, saw 9

Skipping line 144058: expected 8 fields, saw 9
Skipping line 150789: expected 8 fields, saw 9
Skipping line 157128: expected 8 fields, saw 9
Skipping line 180189: expected 8 fields, saw 9
Skipping line 185738: expected 8 fields, saw 9

Skipping line 209388: expected 8 fields, saw 9
Skipping line 220626: expected 8 fields, saw 9
Skipping line 227933: expected 8 fields, saw 11
Skipping line 228957: expected 8 fields, saw 10
Skipping line 245933: expected 8 fields, saw 9
Skipping line 251296: expected 8 fields, saw 9
Skipping line 259941: expected 8 fields, saw 9
Skipping line 261529: expected 8 fields, saw 9

/home/revant/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2714: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
ratings = ratings[ratings['ISBN'].isin(items['ISBN'])]

density = (float(len(ratings))/(len(np.unique(ratings['User-ID']))*len(np.unique(ratings['ISBN']))))*100
print(density) 
print ( len(ratings['User-ID'].unique()) , len(ratings['ISBN'].unique()) )

0.00376224098723
(68091, 149836)

In [8]:
len(ratings['User-ID'].unique())

68091

In [9]:
len(ratings['ISBN'].unique())

149836

In [15]:
import sys
sys.version_info[0]

2

In [16]:
a = ratings.groupby('ISBN').filter(lambda x: len(x) >= 10)
densityi = (float(len(a))/(len(np.unique(a['User-ID']))*len(np.unique(a['ISBN']))))*100
print "Density after filtering items: "+str(densityi) #0.061
print "Users: "+str(len(np.unique(a['User-ID'])))+ " items: "+str(len(np.unique(a['ISBN'])))

Density after filtering items: 0.064999538504
Users: 39365 items: 5444

In [17]:
ratings[]2

         User-ID        ISBN  Book-Rating
8         276744  038550120X            7
16        276747  0060517794            9
19        276747  0671537458            9
20        276747  0679776818            8
28        276754  0684867621            8
29        276755  0451166892            5
33        276762  0380711524            5
83        276788  0345443683            8
84        276788  043935806X            7
85        276788  055310666X           10
86        276796  0330332775            5
97        276798  3548603203            6
109       276804  0440498058            8
133       276822  0060096195           10
137       276822  0375821813            9
145       276822  0786817070           10
158       276828  2253150711            7
163       276830  0440225825            9
165       276832  0345446860            5
168       276837  0380005239            5
177       276847  3404148576            8
179       276847  3423071516           10
210       276847  3551551677           10
211       276847  3551551685           10
212       276847  3551551693           10
213       276847  3551551936           10
238       276850  0449217264            7
280       276859  0836218833           10
281       276859  0836220889           10
289       276861  3423201509           10
...          ...         ...          ...
1149564   276680  0452283205            7
1149575   276680  0679410325            9
1149580   276680  0679771476            7
1149584   276680  0684826127            6
1149589   276680  0688163165           10
1149590   276680  0688163173           10
1149592   276680  0743203631            7
1149604   276680  0743486226            6
1149627   276680  1573222038           10
1149629   276680  1573229083            7
1149637   276680  1931561648            9
1149639   276681  0060809833           10
1149640   276681  0060930535            9
1149641   276681  0060938455            9
1149646   276681  0399144463            8
1149647   276681  0446677450            8
1149654   276683  0553262505            7
1149657   276685  0684195305            5
1149669   276688  031208188X           10
1149697   276688  044661193X            7
1149711   276688  0553566040            6
1149713   276688  0553572512            7
1149714   276688  0553575090            7
1149715   276688  0553575104            6
1149738   276688  0688156134            8
1149743   276688  0836218655           10
1149744   276688  0836236688           10
1149761   276704  0345386108            6
1149771   276704  0743211383            7
1149777   276709  0515107662           10

[139296 rows x 3 columns]